workflows:
  ios-ipa:
    name: Build iOS IPA

    environment:
      flutter: stable
      xcode: latest
      cocoapods: default

    scripts:
      - name: Flutter Pub Get
        script: |
          flutter clean
          flutter pub get

      - name: Install Pods
        script: |
          cd ios
          rm -rf Pods
          rm -f Podfile.lock
          pod deintegrate || true
          pod install --repo-update
          cd ..

      - name: Build IPA
        script: |
          flutter build ipa --release --export-method ad-hoc

    artifacts:
      - build/ios/ipa/*.ipa
      - build/ios/archive/*.xcarchive
